If:
  PathMatch: '.*[.](cpp|cc|cxx|C|hpp|hh|hxx|H)'
  PathExclude:
    - '.*/arduino-language-server[^/]*/build/.*'
    - '/home/om/[.]arduino15/packages/.*'
    - '/home/om/Arduino/libraries/.*'
    - '.*[.]ino[.]cpp'
CompileFlags:
  Add: [-std=c++26]

---
If:
  PathMatch:
    - '.*/arduino-language-server[^/]*/build/.*'
    - '/home/om/[.]arduino15/packages/.*'
    - '/home/om/Arduino/libraries/.*'
CompileFlags:
  Add: [-nostdlibinc]
