# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows
    # gaps_in = 0
    # gaps_out = 0

    # Use master layout instead of dwindle
    # layout = master
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    rounding = 8
}

# Disable transparency for selected apps (added by Oscar). Added no-transparency rules for:
# paraview, ghostty, brave, okular, obsidian, OBS Studio, LabPlot, Drawy, FreeCAD, gimp, inkscape.
windowrule = tag -default-opacity, match:class ^(paraview|ParaView|com\.mitchellh\.ghostty|brave-browser|org\.kde\.okular|okular|obsidian|md\.obsidian\.Obsidian|com\.obsproject\.Studio|LabPlot|labplot|org\.kde\.labplot|org\.kde\.labplot2|Drawy|drawy|org\.kde\.drawy|FreeCAD|org\.freecad\.FreeCAD|gimp|Gimp|org\.gimp\.GIMP|inkscape|org\.inkscape\.Inkscape)$
windowrule = tag -chromium-based-browser, match:class brave-browser # Remove Omarchy's browser tag (tag -chromium-based-browser) so Brave does not get browser-specific opacity
windowrule = opacity 1 1, match:class ^(paraview|ParaView|com\.mitchellh\.ghostty|brave-browser|org\.kde\.okular|okular|obsidian|md\.obsidian\.Obsidian|com\.obsproject\.Studio|LabPlot|labplot|org\.kde\.labplot|org\.kde\.labplot2|Drawy|drawy|org\.kde\.drawy|FreeCAD|org\.freecad\.FreeCAD|gimp|Gimp|org\.gimp\.GIMP|inkscape|org\.inkscape\.Inkscape)$
